
---
events:
  -
    kind: "message-v1"
    backtrace:
<<<<<<< Updated upstream
      - "C:/Users/infwtx851/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
=======
      - "C:/Users/youse/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
>>>>>>> Stashed changes
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
